name: custom environment variables

on: [pull_request, issues]

# These variables are available on all actions/commands in the workflow
env:
  MY_GLOBAL_VAR_1: "Use me anywhere"

jobs:
  job-1:
    runs-on: ubuntu-latest
    
    # These vars are only available for job-1
    
    env:
      MY_JOB_SCOPED_VAR_1: "use me in any step within this job"
      
    steps:
      - uses: some-public/action@v1
      
      # These vars are available only on this step
