--- 
MY_GLOBAL_VAR_1: "“use me anywhere”"
MY_JOB_SCOPED_VAR_1: "“use me in any step within this job”"
MY_STEP_VAR: "“Use me directly with some-public/action@v1"
env: ~
job-1: ~
jobs: ~
name: "The designated name of the entire workflow file"
runs-on: ubuntu-latest
steps: 
  - 
    uses: some-public/action@v1
true: 
  - pull_request
  - issues
